<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>6a7c427d-88d8-4c55-9754-ce4f458862d0</UserSecretsId>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\AiService.Application\AiService.Application.csproj"/>
        <ProjectReference Include="..\AiService.Infrastructure\AiService.Infrastructure.csproj"/>
    </ItemGroup>
</Project>
