// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskService.Persistence.Context;

#nullable disable

namespace TaskService.Persistence.TaskService.TaskService.Persistence.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20260526165627_AddDemoTasksSeed")]
    partial class AddDemoTasksSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskService.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("trophy");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b4c0a8c-d745-4bd5-9f78-aa142f7de669"),
                            Code = "helper-10",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполнить 10 заданий",
                            Icon = "star",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 100,
                            SortOrder = 1,
                            TargetValue = 10,
                            Title = "Юный помощник",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f6a4f768-3a43-41cf-9d0e-bbc868710f19"),
                            Code = "daily-rocket",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполнить 3 задания за день",
                            Icon = "zap",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 50,
                            SortOrder = 2,
                            TargetValue = 3,
                            Title = "Быстрая ракета",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a8fbe2e9-2f0f-4f0d-8dfc-6f6d6efc5a67"),
                            Code = "streak-7",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Серия 7 дней подряд",
                            Icon = "flame",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 200,
                            SortOrder = 3,
                            TargetValue = 7,
                            Title = "Ни дня без дела!",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("419a7a1b-4816-4d5f-9f25-28c52f4a5a42"),
                            Code = "sharp-shooter",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполнить 5 сложных заданий",
                            Icon = "target",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 150,
                            SortOrder = 4,
                            TargetValue = 5,
                            Title = "Точный стрелок",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0e87458a-a61a-4e76-9f46-30f3e9a9f329"),
                            Code = "weekly-king",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Стать первым в рейтинге недели",
                            Icon = "crown",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 300,
                            SortOrder = 5,
                            TargetValue = 1,
                            Title = "Король недели",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b349e60d-9a3d-4b7c-8c26-93a2418f9644"),
                            Code = "task-master-50",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполнить 50 заданий",
                            Icon = "trophy",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 500,
                            SortOrder = 6,
                            TargetValue = 50,
                            Title = "Мастер задач",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-2222-4000-8000-000000000001"),
                            Code = "early-bird",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполнить задание до 9:00 утра 5 раз",
                            Icon = "alarm-clock",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 120,
                            SortOrder = 7,
                            TargetValue = 5,
                            Title = "Ранняя пташка",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-2222-4000-8000-000000000002"),
                            Code = "streak-30",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Серия 30 дней подряд",
                            Icon = "shield",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 800,
                            SortOrder = 8,
                            TargetValue = 30,
                            Title = "Железная воля",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-2222-4000-8000-000000000003"),
                            Code = "first-purchase",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Потратить баллы в магазине наград",
                            Icon = "shopping-cart",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 50,
                            SortOrder = 9,
                            TargetValue = 1,
                            Title = "Первая покупка",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-2222-4000-8000-000000000004"),
                            Code = "helper-100",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполнить 100 заданий",
                            Icon = "medal",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 1000,
                            SortOrder = 10,
                            TargetValue = 100,
                            Title = "Супер-помощник",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-2222-4000-8000-000000000005"),
                            Code = "creative-mind",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполнить 10 заданий из категории творчество",
                            Icon = "palette",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 200,
                            SortOrder = 11,
                            TargetValue = 10,
                            Title = "Творческий ум",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-2222-4000-8000-000000000006"),
                            Code = "team-player",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполнить 5 семейных миссий",
                            Icon = "users",
                            IsActive = true,
                            IsHidden = false,
                            RewardXp = 250,
                            SortOrder = 12,
                            TargetValue = 5,
                            Title = "Командный игрок",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-2222-4000-8000-000000000007"),
                            Code = "secret-legend",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "???",
                            Icon = "gem",
                            IsActive = true,
                            IsHidden = true,
                            RewardXp = 5000,
                            SortOrder = 13,
                            TargetValue = 500,
                            Title = "Легенда",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.AchievementProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProgressValue")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId", "UserId")
                        .IsUnique();

                    b.ToTable("achievement_progress", (string)null);
                });

            modelBuilder.Entity("TaskService.Domain.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("target");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Recurrence")
                        .HasColumnType("integer");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("missions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f68d135-3a90-4f50-9b8e-5d0af9f3e5a1"),
                            Code = "complete-three-daily-tasks",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполни 3 любых задания до конца дня",
                            Icon = "check-circle-2",
                            IsActive = true,
                            Recurrence = 1,
                            RewardXp = 50,
                            SortOrder = 1,
                            TargetValue = 3,
                            Title = "Выполни 3 задания",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cde995cd-88ee-44bb-9e1a-0ebbf35fb2a7"),
                            Code = "earn-twenty-points",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Получи 20 очков за выполнение задач",
                            Icon = "zap",
                            IsActive = true,
                            Recurrence = 1,
                            RewardXp = 75,
                            SortOrder = 2,
                            TargetValue = 20,
                            Title = "Заработай 20 очков",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0c6aa8d5-8a2e-4d6a-9d24-62dd9a2c9df4"),
                            Code = "login-seven-days",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Заходи в приложение каждый день",
                            Icon = "flame",
                            IsActive = true,
                            Recurrence = 1,
                            RewardXp = 100,
                            SortOrder = 3,
                            TargetValue = 7,
                            Title = "Логинься 7 дней",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8b54ff19-8e0a-44f2-9315-06cb5c076d16"),
                            Code = "complete-hard-task",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполни задание со сложностью 4+ звёзды",
                            Icon = "target",
                            IsActive = true,
                            Recurrence = 1,
                            RewardXp = 60,
                            SortOrder = 4,
                            TargetValue = 1,
                            Title = "Выполни сложное задание",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7f54a8a1-78f1-4e37-8cf1-02ab142d5699"),
                            Code = "complete-twenty-weekly",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполни 20 заданий за неделю",
                            Icon = "check-circle-2",
                            IsActive = true,
                            Recurrence = 2,
                            RewardXp = 250,
                            SortOrder = 5,
                            TargetValue = 20,
                            Title = "Выполни 20 заданий",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3a75fa50-7f45-4fa2-98c2-58ff75a1dd1f"),
                            Code = "unlock-three-badges",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Разблокируй 3 достижения на этой неделе",
                            Icon = "award",
                            IsActive = true,
                            Recurrence = 2,
                            RewardXp = 300,
                            SortOrder = 6,
                            TargetValue = 3,
                            Title = "Получи 3 бейджа",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-1111-4000-8000-000000000001"),
                            Code = "morning-routine",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполни утреннее задание до 10:00",
                            Icon = "sunrise",
                            IsActive = true,
                            Recurrence = 1,
                            RewardXp = 40,
                            SortOrder = 7,
                            TargetValue = 1,
                            Title = "Утренний ритуал",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-1111-4000-8000-000000000002"),
                            Code = "help-family-member",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Помоги другому члену семьи с задачей",
                            Icon = "heart-handshake",
                            IsActive = true,
                            Recurrence = 1,
                            RewardXp = 80,
                            SortOrder = 8,
                            TargetValue = 1,
                            Title = "Семейный помощник",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-1111-4000-8000-000000000003"),
                            Code = "earn-hundred-points-weekly",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Заработай 100 очков за неделю",
                            Icon = "coins",
                            IsActive = true,
                            Recurrence = 2,
                            RewardXp = 200,
                            SortOrder = 9,
                            TargetValue = 100,
                            Title = "Сотня за неделю",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-1111-4000-8000-000000000004"),
                            Code = "five-different-categories",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Выполни задачи из 5 разных категорий за неделю",
                            Icon = "layers",
                            IsActive = true,
                            Recurrence = 2,
                            RewardXp = 180,
                            SortOrder = 10,
                            TargetValue = 5,
                            Title = "Разносторонний",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.MissionProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnchorDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProgressValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("MissionId", "UserId")
                        .IsUnique();

                    b.ToTable("mission_progress", (string)null);
                });

            modelBuilder.Entity("TaskService.Domain.Entities.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TaskId");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("TaskService.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<string>("EvidenceContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EvidenceFileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("EvidenceFileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("EvidenceRequirement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("EvidenceStoragePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("EvidenceUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceUploadedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("PendingApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("RewardXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<bool>("StartedByChild")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000002",
                            Completed = true,
                            CompletedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Выбери любую книгу из домашней библиотеки и прочитай минимум 10 страниц",
                            Difficulty = 2,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 5,
                            RewardXp = 100,
                            StartedByChild = true,
                            Title = "Прочитать 10 страниц книги",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000002",
                            Completed = true,
                            CompletedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Пропылесосить, сложить вещи, вытереть пыль на столе",
                            Difficulty = 1,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 2,
                            RewardXp = 80,
                            StartedByChild = true,
                            Title = "Убраться в своей комнате",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000002",
                            Completed = false,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Решить все задания из учебника: упражнения 5.1 - 5.4",
                            Difficulty = 3,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 10,
                            RewardXp = 120,
                            StartedByChild = true,
                            Title = "Сделать домашнюю работу по математике",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000002",
                            Completed = false,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Запомнить новые слова и написать предложение с каждым",
                            Difficulty = 2,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 5,
                            RewardXp = 100,
                            StartedByChild = false,
                            Title = "Выучить 5 английских слов"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000005"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000002",
                            Completed = false,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Помыть всю посуду и протереть поверхность раковины",
                            Difficulty = 1,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 2,
                            RewardXp = 80,
                            StartedByChild = false,
                            Title = "Помыть посуду после ужина"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000006"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000002",
                            Completed = false,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Создай рисунок нашей семьи — можно в любой технике!",
                            Difficulty = 4,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 20,
                            RewardXp = 140,
                            StartedByChild = false,
                            Title = "Нарисовать семейный портрет"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000007"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000003",
                            Completed = true,
                            CompletedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Проверить влажность почвы и полить цветы там, где нужно",
                            Difficulty = 1,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 2,
                            RewardXp = 80,
                            StartedByChild = true,
                            Title = "Полить все комнатные цветы",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000008"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000003",
                            Completed = true,
                            CompletedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "«Зимнее утро» Пушкина — выучить и прочитать маме или папе",
                            Difficulty = 3,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 10,
                            RewardXp = 120,
                            StartedByChild = true,
                            Title = "Выучить стихотворение наизусть",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000009"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000003",
                            Completed = false,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Разложить тарелки, приборы и стаканы для всей семьи",
                            Difficulty = 1,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 2,
                            RewardXp = 80,
                            StartedByChild = false,
                            Title = "Помочь накрыть на стол к обеду"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000010"),
                            AssignedToUserId = "a1000000-0000-0000-0000-000000000003",
                            Completed = false,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Приседания, прыжки, растяжка — 15 минут активности",
                            Difficulty = 2,
                            EvidenceRequirement = 0,
                            PendingApproval = true,
                            RewardPoints = 5,
                            RewardXp = 100,
                            StartedByChild = true,
                            Title = "Сделать зарядку 15 минут",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000011"),
                            Completed = false,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Придумай правила новой игры, в которую можно играть всей семьёй",
                            Difficulty = 3,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 10,
                            RewardXp = 120,
                            StartedByChild = false,
                            Title = "Придумать семейную игру"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000012"),
                            Completed = false,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1000000-0000-0000-0000-000000000001",
                            Description = "Поможи соседям или сделай что-то приятное для людей рядом",
                            Difficulty = 4,
                            EvidenceRequirement = 0,
                            PendingApproval = false,
                            RewardPoints = 20,
                            RewardXp = 140,
                            StartedByChild = false,
                            Title = "Сделать добрый поступок для соседей"
                        });
                });

            modelBuilder.Entity("TaskService.Domain.Entities.AchievementProgress", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("TaskService.Domain.Entities.MissionProgress", b =>
                {
                    b.HasOne("TaskService.Domain.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });
#pragma warning restore 612, 618
        }
    }
}
