<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FamilyQuest.Gateway.Domain\FamilyQuest.Gateway.Domain.csproj" />
      <ProjectReference Include="..\FamilyQuest.Gateway.Common\FamilyQuest.Gateway.Common.csproj" />
    </ItemGroup>

</Project>
